import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../ar.dart';
import '../models/user_profile.dart';
import '../services/storage_service.dart';
import '../utils/date_utils.dart';

class DoctorReportSheet extends StatelessWidget {
  final StorageService storageService;
  final UserProfile profile;

  const DoctorReportSheet({
    super.key,
    required this.storageService,
    required this.profile,
  });

  String _generateReportText() {
    final now = DateTime.now();
    final medicines = storageService.getMedicines(forProfileId: profile.id);
    final logs = storageService.getLogs();
    final painLogs = logs.where((l) => l.isPainkiller).toList();
    final recentLogs = logs
        .where((l) => now.difference(l.takenAt).inDays <= 7)
        .toList();

    final buffer = StringBuffer();
    buffer.writeln(Ar.reportDocHeader);
    buffer.writeln('===================================');
    buffer.writeln(
      '${Ar.reportPatientName} ${profile.name} (${profile.relation})',
    );
    buffer.writeln(
      '${Ar.reportGeneratedDate} ${AppDateUtils.formatFullDate(now)}',
    );
    buffer.writeln('===================================\n');

    buffer.writeln(Ar.reportMedsAndStock);
    if (medicines.isEmpty) {
      buffer.writeln(Ar.reportNoMeds);
    } else {
      for (final med in medicines) {
        final type = med.isPainkiller ? Ar.painkillerAsNeeded : Ar.treatmentTag;
        buffer.writeln('• *${med.name}* ($type)');
        buffer.writeln(
          '  - ${Ar.reportDoseLabel} ${med.pillsPerDose} ${med.unitLabel}',
        );
        buffer.writeln(
          '  - ${Ar.reportRemainingStock} ${med.totalPills} ${med.unitLabel}',
        );
        if (med.isTreatment && med.scheduledTimes.isNotEmpty) {
          final times = med.scheduledTimes
              .map((t) => '${t.hour}:${t.minute.toString().padLeft(2, '0')}')
              .join(', ');
          buffer.writeln('  - ${Ar.reportDailyTimes} $times');
        }
      }
    }

    buffer.writeln('\n${Ar.reportAdherenceStats7Days}');
    buffer.writeln(
      '• ${Ar.reportTotalDosesTaken} ${recentLogs.length} ${Ar.unitDoses}',
    );

    buffer.writeln('\n${Ar.reportPainAndPainkillersLog}');
    if (painLogs.isEmpty) {
      buffer.writeln(Ar.reportNoRecentPain);
    } else {
      for (final pl in painLogs.take(5)) {
        final timeStr = AppDateUtils.formatDateTime(pl.takenAt);
        final painScore = pl.painLevel != null
            ? '${pl.painLevel}/10'
            : Ar.reportNotSpecified;
        final reason = pl.notes ?? Ar.reportGeneralPain;
        buffer.writeln('• $timeStr');
        buffer.writeln('  - ${Ar.reportPainkiller} ${pl.medicineName}');
        buffer.writeln(
          '  - ${Ar.reportPainIntensity} $painScore | ${Ar.reportPainSite} $reason',
        );
      }
    }

    buffer.writeln('\n===================================');
    buffer.writeln(Ar.reportAutoGeneratedFooter);
    return buffer.toString();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final reportText = _generateReportText();

    return Container(
      height: MediaQuery.of(context).size.height * 0.8,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: theme.scaffoldBackgroundColor,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(28)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey.withValues(alpha: 0.4),
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Expanded(
                child: Row(
                  children: [
                    Icon(
                      Icons.assignment_turned_in_rounded,
                      color: Color(0xFF0D9488),
                      size: 24,
                    ),
                    SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        Ar.reportSheetTitle,
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              IconButton(
                onPressed: () => Navigator.pop(context),
                icon: const Icon(Icons.close),
              ),
            ],
          ),
          const SizedBox(height: 12),

          // Scrollable Report Preview
          Expanded(
            child: Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: theme.cardColor,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(
                  color: theme.dividerColor.withValues(alpha: 0.3),
                ),
              ),
              child: SingleChildScrollView(
                child: SelectableText(
                  reportText,
                  style: const TextStyle(
                    fontSize: 13.5,
                    height: 1.5,
                    fontFamily: 'monospace',
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Action Buttons: Copy to WhatsApp & Print
          Row(
            children: [
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: () async {
                    await Clipboard.setData(ClipboardData(text: reportText));
                    if (!context.mounted) return;
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text(Ar.reportCopiedSuccess),
                        backgroundColor: Color(0xFF10B981),
                      ),
                    );
                  },
                  icon: const Icon(Icons.copy_rounded),
                  label: const Text(Ar.shareViaWhatsApp),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    backgroundColor: const Color(0xFF0D9488),
                    foregroundColor: Colors.white,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
